/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import type { SvgComponentType } from 'src/types';

import ebikeConversionFullHubFLp from './ebike/ebike-conversion-full-hub_f-lp.svg';
import ebikeConversionFullHubFMp from './ebike/ebike-conversion-full-hub_f-mp.svg';
import ebikeConversionFullHubF from './ebike/ebike-conversion-full-hub_f.svg';
import ebikeConversionFullHubRHp from './ebike/ebike-conversion-full-hub_r-hp.svg';
import ebikeConversionFullHubRIp from './ebike/ebike-conversion-full-hub_r-ip.svg';
import ebikeConversionFullHubRMp from './ebike/ebike-conversion-full-hub_r-mp.svg';
import ebikeConversionFullHubR from './ebike/ebike-conversion-full-hub_r.svg';
import ebikeConversionFullMidHp from './ebike/ebike-conversion-full-mid-hp.svg';
import ebikeConversionFullMidIp from './ebike/ebike-conversion-full-mid-ip.svg';
import ebikeConversionFullMidMp from './ebike/ebike-conversion-full-mid-mp.svg';
import ebikeConversionFullMid from './ebike/ebike-conversion-full-mid.svg';
import ebikeConversionFull from './ebike/ebike-conversion-full.svg';
import ebikeConversionHtHubFCruiser from './ebike/ebike-conversion-ht-hub_f-cruiser.svg';
import ebikeConversionHtHubFLp from './ebike/ebike-conversion-ht-hub_f-lp.svg';
import ebikeConversionHtHubFMp from './ebike/ebike-conversion-ht-hub_f-mp.svg';
import ebikeConversionHtHubF from './ebike/ebike-conversion-ht-hub_f.svg';
import ebikeConversionHtHubRCruiser from './ebike/ebike-conversion-ht-hub_r-cruiser.svg';
import ebikeConversionHtHubRHp from './ebike/ebike-conversion-ht-hub_r-hp.svg';
import ebikeConversionHtHubRMp from './ebike/ebike-conversion-ht-hub_r-mp.svg';
import ebikeConversionHtHubR from './ebike/ebike-conversion-ht-hub_r.svg';
import ebikeConversionHtMidLp from './ebike/ebike-conversion-ht-mid-lp.svg';
import ebikeConversionHtMidMp from './ebike/ebike-conversion-ht-mid-mp.svg';
import ebikeConversionHtMid from './ebike/ebike-conversion-ht-mid.svg';
import ebikeConversionHt from './ebike/ebike-conversion-ht.svg';
import ebikeConversion from './ebike/ebike-conversion.svg';
import ebikeFactoryFull from './ebike/ebike-factory-full.svg';
import ebikeFactoryHt from './ebike/ebike-factory-ht.svg';
import ebikeFactory from './ebike/ebike-factory.svg';
import ebikeMonsterHillC from './ebike/ebike-monster-hill_c.svg';
import ebikeMonsterLight from './ebike/ebike-monster-light.svg';
import ebikeMonsterSpeed from './ebike/ebike-monster-speed.svg';
import ebikeMonster from './ebike/ebike-monster.svg';
import emotoConversionHub from './emoto/emoto-conversion-hub.svg';
import emotoConversionMid from './emoto/emoto-conversion-mid.svg';
import emotoFactory from './emoto/emoto-factory.svg';
import emoto from './emoto/emoto.svg';
import other from './other.svg';

export const EbikeConversion: SvgComponentType = ebikeConversion;
export const EbikeConversionFull: SvgComponentType = ebikeConversionFull;
export const EbikeConversionFullHubF: SvgComponentType = ebikeConversionFullHubF;
export const EbikeConversionFullHubFLp: SvgComponentType = ebikeConversionFullHubFLp;
export const EbikeConversionFullHubFMp: SvgComponentType = ebikeConversionFullHubFMp;
export const EbikeConversionFullHubR: SvgComponentType = ebikeConversionFullHubR;
export const EbikeConversionFullHubRHp: SvgComponentType = ebikeConversionFullHubRHp;
export const EbikeConversionFullHubRIp: SvgComponentType = ebikeConversionFullHubRIp;
export const EbikeConversionFullHubRMp: SvgComponentType = ebikeConversionFullHubRMp;
export const EbikeConversionFullMid: SvgComponentType = ebikeConversionFullMid;
export const EbikeConversionFullMidHp: SvgComponentType = ebikeConversionFullMidHp;
export const EbikeConversionFullMidIp: SvgComponentType = ebikeConversionFullMidIp;
export const EbikeConversionFullMidMp: SvgComponentType = ebikeConversionFullMidMp;
export const EbikeConversionHt: SvgComponentType = ebikeConversionHt;
export const EbikeConversionHtHubF: SvgComponentType = ebikeConversionHtHubF;
export const EbikeConversionHtHubFCruiser: SvgComponentType = ebikeConversionHtHubFCruiser;
export const EbikeConversionHtHubFLp: SvgComponentType = ebikeConversionHtHubFLp;
export const EbikeConversionHtHubFMp: SvgComponentType = ebikeConversionHtHubFMp;
export const EbikeConversionHtHubR: SvgComponentType = ebikeConversionHtHubR;
export const EbikeConversionHtHubRCruiser: SvgComponentType = ebikeConversionHtHubRCruiser;
export const EbikeConversionHtHubRHp: SvgComponentType = ebikeConversionHtHubRHp;
export const EbikeConversionHtHubRMp: SvgComponentType = ebikeConversionHtHubRMp;
export const EbikeConversionHtMid: SvgComponentType = ebikeConversionHtMid;
export const EbikeConversionHtMidLp: SvgComponentType = ebikeConversionHtMidLp;
export const EbikeConversionHtMidMp: SvgComponentType = ebikeConversionHtMidMp;
export const EbikeFactory: SvgComponentType = ebikeFactory;
export const EbikeFactoryFull: SvgComponentType = ebikeFactoryFull;
export const EbikeFactoryHt: SvgComponentType = ebikeFactoryHt;
export const EbikeMonster: SvgComponentType = ebikeMonster;
export const EbikeMonsterHillC: SvgComponentType = ebikeMonsterHillC;
export const EbikeMonsterLight: SvgComponentType = ebikeMonsterLight;
export const EbikeMonsterSpeed: SvgComponentType = ebikeMonsterSpeed;
export const Emoto: SvgComponentType = emoto;
export const EmotoConversionHub: SvgComponentType = emotoConversionHub;
export const EmotoConversionMid: SvgComponentType = emotoConversionMid;
export const EmotoFactory: SvgComponentType = emotoFactory;
export const Other: SvgComponentType = other;
